services:
  backend:
    image: docker.alexandra.dk/coral-data-collection-backend:latest
    container_name: coral-data-collection-backend
    restart: unless-stopped
    volumes:
      - ./data:${CORAL_DATA_DIR}
    ports:
      - "${CORAL_PORT}:${CORAL_PORT}"
    expose:
      - ${CORAL_PORT}
    environment:
     - CORAL_PORT=${CORAL_PORT}
     - CORAL_DATA_DIR=${CORAL_DATA_DIR}

  frontend:
    image: docker.alexandra.dk/coral-data-collection-app:latest
    container_name: coral-data-collection-app
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:80"