services:
  backend:
    image: docker.alexandra.dk/coral-data-collection-backend:latest
    container_name: coral-data-collection-backend
    restart: unless-stopped
    volumes:
      - ./audio_files:/audio_files
      - ./db.sqlite3:/db.sqlite3
    ports:
      - "3333:3333"
    expose:
      - 3333
    environment:
     - PORT_ENV=3333
     - AUDIO_FOLDER_ENV=audio_files


  frontend:
    image: docker.alexandra.dk/coral-data-collection-app:latest
    container_name: coral-data-collection-app
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:80"